### ISSUE TITLE
Resources missing in repo under RouteFinder/Map/

### ISSUE THREAD

**Issue by DevCas1** [JustinDMS/Prime-Tool#1]
The project references folder `RouteFinder/Map/Chozo Ruins/`, yet the whole `/Chozo Ruins/` folder is missing from the `Map` folder in the repository.
Maybe more are missing, but this is the first the debugger is nagging about:
```
E 0:00:07:0462   Resource_RouteFinder.gd:24 @ @implicit_new(): Resource file not found: res://RouteFinder/Map/Chozo Ruins/Antechamber.glb.
  <C++ Error>    Condition "!file_check->file_exists(p_path)" is true. Returning: Ref<Resource>()
  <C++ Source>   core/io/resource_loader.cpp:227 @ _load()
  <Stack Trace>  Resource_RouteFinder.gd:24 @ @implicit_new()
```
Could these resources be added to the source?
Wanted to take a look and see if I could perhaps add the elevator indicators like how DrakePHOSE explained, but couldn't get the project to run because of the aforementioned issue.

**Comment by JustinDMS** [comment]
The .glb files have been added to the repository
